services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    ports:
      - '3000:3000'
    environment:
      API_BASE_URL: http://localhost:3000
      CACHE_CLEANUP_OLDER_THAN_DAYS: '30'
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data: