apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-dind.fullname" . }}
  labels:
    {{- include "docker-dind.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "docker-dind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "docker-dind.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "docker-dind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ if (hasPrefix "@" .Values.image.tag) }}{{ .Values.image.tag }}{{ else }}:{{ .Values.image.tag | default (regexReplaceAllLiteral "^v" .Chart.AppVersion "") }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: docker
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DOCKER_HOST
              value: {{ .Values.docker.host }}
            {{- if .Values.firewall.enabled }}
            - name: FIREWALL_POD_CIDR
              value: {{ .Values.firewall.podCIDR | quote }}
            - name: FIREWALL_NODE_CIDR
              value: {{ .Values.firewall.nodeCIDR | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: docker-config
              mountPath: C:/docker-config
            {{- if .Values.persistence.enabled }}
            - name: docker-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
      volumes:
        - name: docker-config
          configMap:
            name: {{ include "docker-dind.fullname" . }}
        {{- if .Values.persistence.enabled }}
        - name: docker-data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "docker-dind.fullname" . }}
          {{- end }}
        {{- end }}
