apiVersion: v2
name: docker-dind
description: Windows Docker-in-Docker service with TCP endpoint
type: application
version: 0.4.2-dev.10
appVersion: "28.3.1"
keywords:
  - docker
  - dind
  - windows
  - tcp
home: https://github.com/matfax/github-runner
sources:
  - https://github.com/matfax/github-runner/tree/main/docker-dind
maintainers:
  - name: matfax
    email: mat@fax.fyi
